export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PROJECT = "GET_PROJECT";
export const ADD_PROJECT = "ADD_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const CLEAR_PROJECT = "CLEAR_PROJECT";

export const ADD_SECTION = "ADD_SECTION";
export const UPDATE_SECTION = "UPDATE_SECTION";
export const DELETE_SECTION = "DELETE_SECTION";

export const ADD_TASK = "ADD_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
export const DELETE_TASK = "DELETE_TASK";

export const SHOW_ADD_PROJECT_MODAL = "SHOW_ADD_PROJECT_MODAL";
export const HIDE_ADD_PROJECT_MODAL = "HIDE_ADD_PROJECT_MODAL";
export const SHOW_UPDATE_PROJECT_MODAL = "SHOW_UPDATE_PROJECT_MODAL";
export const HIDE_UPDATE_PROJECT_MODAL = "HIDE_UPDATE_PROJECT_MODAL";
export const SHOW_DELETE_PROJECT_MODAL = "SHOW_DELETE_PROJECT_MODAL";
export const HIDE_DELETE_PROJECT_MODAL = "HIDE_DELETE_PROJECT_MODAL";
export const SHOW_TASK_MODAL = "SHOW_TASK_MODAL";
export const HIDE_TASK_MODAL = "HIDE_TASK_MODAL";

export const GET_ERRORS = "GET_ERRORS";
