export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PROJECT = "GET_PROJECT";
export const ADD_PROJECT = "ADD_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const CLEAR_PROJECT = "CLEAR_PROJECT";

export const SHOW_ADD_PROJECT_MODAL = "SHOW_ADD_PROJECT_MODAL";
export const HIDE_ADD_PROJECT_MODAL = "HIDE_ADD_PROJECT_MODAL";
export const SHOW_UPDATE_PROJECT_MODAL = "SHOW_UPDATE_PROJECT_MODAL";
export const HIDE_UPDATE_PROJECT_MODAL = "HIDE_UPDATE_PROJECT_MODAL";

export const GET_ERRORS = "GET_ERRORS";
